version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch-basic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - payment-basic-network
    ulimits:
      memlock:
        soft: -1
        hard: -1

  server_api:
    build:
      context: .
      dockerfile: Dockerfile.server.simple
    container_name: server-api-basic
    environment:
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
      LOG_LEVEL: INFO
      APP_ENV: production
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
    networks:
      - payment-basic-network
    restart: unless-stopped

volumes:
  elasticsearch_data:
    driver: local

networks:
  payment-basic-network:
    driver: bridge
