version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch-server
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - payment-server-network
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  server_api:
    build:
      context: .
      dockerfile: Dockerfile.server.simple
    container_name: server-api-server
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - LOG_LEVEL=INFO
      - APP_ENV=production
    expose:
      - "8000"
    volumes:
      - ./logs:/app/logs
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - payment-server-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: nginx-simple
    ports:
      - "80:80"
    volumes:
      - ./nginx/simple-nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server_api
    networks:
      - payment-server-network
    restart: unless-stopped

volumes:
  elasticsearch_data:
    driver: local

networks:
  payment-server-network:
    driver: bridge
