version: '3.8'

services:
  ai-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - WORKERS=2
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  ai-service-dev:
    build: .
    ports:
      - "8001:8000"
    environment:
      - APP_ENV=development
      - DEBUG=true
      - NLTK_DATA=/app/nltk_data
      - LOGGING_CONFIG=/app/src/ai_service/config/logging_dev.yml
    volumes:
      - ./src/ai_service/main.py:/app/src/ai_service/main.py
      - ./src/ai_service/services:/app/src/ai_service/services
      - ./src/ai_service/utils:/app/src/ai_service/utils
      - ./config.py:/app/config.py
      - ./logs:/app/logs
    command: ["sh", "-c", "mkdir -p /app/logs && poetry run uvicorn src.ai_service.main:app --host 0.0.0.0 --port 8000 --reload"]
    profiles:
      - dev
